// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CasaDeEmpeño.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240630075617_AddEstadoRegistroToDevoluciones")]
    partial class AddEstadoRegistroToDevoluciones
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CasaDeEmpeño.Models.Devolucion", b =>
                {
                    b.Property<int>("DevolucionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DevolucionID"), 1L, 1);

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstadoRegistro")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaDevolucion")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductoID")
                        .HasColumnType("int");

                    b.HasKey("DevolucionID");

                    b.HasIndex("ProductoID");

                    b.ToTable("Devoluciones");
                });

            modelBuilder.Entity("CasaDeEmpeño.Models.Oferta", b =>
                {
                    b.Property<int>("OfertaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OfertaID"), 1L, 1);

                    b.Property<DateTime>("FechaOferta")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MontoOferta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NombreOfertante")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroCelular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductoID")
                        .HasColumnType("int");

                    b.HasKey("OfertaID");

                    b.HasIndex("ProductoID");

                    b.ToTable("Ofertas");
                });

            modelBuilder.Entity("CasaDeEmpeño.Models.Producto", b =>
                {
                    b.Property<int>("ProductoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductoID"), 1L, 1);

                    b.Property<string>("EstadoProducto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstadoRegistro")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaVencimientoDevolucion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoProducto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValorCalculado")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductoID");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("CasaDeEmpeño.Models.Devolucion", b =>
                {
                    b.HasOne("CasaDeEmpeño.Models.Producto", "Producto")
                        .WithMany("Devoluciones")
                        .HasForeignKey("ProductoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("CasaDeEmpeño.Models.Oferta", b =>
                {
                    b.HasOne("CasaDeEmpeño.Models.Producto", "Producto")
                        .WithMany("Ofertas")
                        .HasForeignKey("ProductoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("CasaDeEmpeño.Models.Producto", b =>
                {
                    b.Navigation("Devoluciones");

                    b.Navigation("Ofertas");
                });
#pragma warning restore 612, 618
        }
    }
}
